<<reconos_preproc>>

#define RRBASETYPE 			<<RRBASETYPE>>
#define RRUBASETYPE			<<RRUBASETYPE>>
#define RRBASETYPEBYTES		<<RRBASETYPEBYTES>>

#if (RRBASETYPEBYTES == 8)
    #define RRUBASETYPEMAX 0xFFFFFFFFFFFFFFFF
#elif (RRBASETYPEBYTES == 4)
    #define RRUBASETYPEMAX 0xFFFFFFFF
#endif
